### ISSUE TITLE
Fix consistency of author first names in bib

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/ACMCompEd2019#1]
ACM conf style uses full first name for references -- but not all bib entries have these.

**Comment by JamesHDavenport** [comment]
My fault - my database doesn’t necessarily have these.

Sent from my iPhone

On 24 Oct 2018, at 02:05, Tom Crick <notifications@github.com<mailto:notifications@github.com>> wrote:


ACM conf style uses full first name for references -- but not all bib entries have these.

**Comment by JamesHDavenport** [comment]
Fixed the one I can easily.  Good enough for a submission, I think.

**Comment by tomcrick** [comment]
Agreed -- can fix rest in camera-ready version.

**Comment by JamesHDavenport** [comment]
OK - now that one's done it's HEA STEM time.


James Davenport
Hebron & Medlock Professor of Information Technology, University of Bath
National Teaching Fellow 2014
OpenMath Content Dictionary Editor
Former Fulbright CyberSecurity Scholar (at New York University)
Chair, IMU Committee on Electronic Information and Communication
Vice-President and Academy Chair, British Computer Society
________________________________

**Comment by tomcrick** [comment]
Now not an issue for IEEE paper style

**Comment by JamesHDavenport** [comment]
There’s a JHD in reference 46, for example.
