### ISSUE TITLE
Quality of Fig.1

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/ACMCompEd2019#2]
Can we improve the quality of Fig.1 in the CEP 2019 paper?

**Comment by JamesHDavenport** [comment]
I think so – are you thinking of changing the colours, specifically the yellow?

**Comment by tomcrick** [comment]
Yes -- can we get decent contrast with yellow parts in greyscale?

**Comment by JamesHDavenport** [comment]
How does v5 look?

**Comment by tomcrick** [comment]
Looks good -- have merged into doc.

**Comment by tomcrick** [comment]
Closed by @JamesHDavenport with commit 9086f9a42077f0991111561225dc7747a10394e9
