### ISSUE TITLE
Too early?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/ACMCompEd2019#6]
- _still early to see any impact, so how this could help further curricula recommendations?_

- _While the context is helpful, the institute remains young, so I am not sure how much there is to learn from it yet (Emphasis on the yet, this is a great initiative, but remains young.)_

- _There is no real assessment or evaluation of the initiative presented or discussion of its impact. I think this is probably because the initiative is still too young to have been meaningfully evaluated for impact. This does not mean that the initiative is not worthwhile – just that it is probably too early on in the project to be producing a paper for publication that tries to extend beyond a white paper or positioning piece._

- _The weakness of this paper is that it is not clear to this author if their efforts will be successful: there is no question they are grounded in fact, but even the authors admit that the time frame and resources for this program are not sufficient to even evaluate ultimate outcomes.  To that end, it is difficult to argue that this provides deeper insight into the effectiveness of the system that they have constructed._

**Comment by tomcrick** [comment]
Still an issue, but one year in now?

**Comment by JamesHDavenport** [comment]
Fair comment, I think!
