### ISSUE TITLE
Link to other examples/initiatives internationally

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/ACMCompEd2019#7]
- _While the authors motivate the need for "something else", where the something else seems to essentially be an umbrella organization, they do not discuss existing alternatives such as microdegrees, moocs, university-industry collaborations, boot camps, coding universities (e.g. https://code.berlin/en/faq/) and so on. Similarly, little discussion on why universities etc should join the initiative is given -- this reviewer is left thinking "how do I take this into my own context?"._

- _Additionally with more room and given the context of CompEd, it would have been useful if the authors had compared and contrasted this initiative with other similar global initiatives._

**Comment by tomcrick** [comment]
Some comments in final section, but perhaps add links to explicit examples?

**Comment by JamesHDavenport** [comment]
I think we'll see what the referees say.

James Davenport
Hebron & Medlock Professor of Information Technology, University of Bath
National Teaching Fellow 2014
OpenMath Content Dictionary Editor
Former Fulbright CyberSecurity Scholar (at New York University)
Chair, IMU Committee on Electronic Information and Communication
Vice-President and Academy Chair, British Computer Society
________________________________

**Comment by tomcrick** [comment]
Closed in commit b53d76650a3b7fcf7d31f134a53bb8580d1fc308
